name: CI

on:
  push:
  pull_request:
  schedule:
  - cron:  '1 0 * * 0'

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Docker image
      if: "!(startsWith(github.ref, 'refs/tags/'))"
      uses: docker/build-push-action@v1
      with:
        repository: physicsillinois/phys-2xx
        path: docker
        dockerfile: docker/Dockerfile
        tags: test
        tag_with_sha: true
        tag_with_ref: true
        push: false
    - name: List Built Images
      run: docker images
    - name: Run test program
      run: >-
        docker run --rm
        --entrypoint /bin/bash
        physicsillinois/phys-2xx:test
        -c "python -m pip list"
